infobip:
  openapi:
    mcp:
      # With auth disabled in mock mode API Base URL is not needed:
      api-base-url: https://example.com
      # OpenAPI specification describing Infobip's SMS API:
      open-api-url: https://api.infobip.com/platform/1/openapi/mcp/sms
      # Running MCP server in mock mode. Tool calls will not
      # result in API calls. Server will return example
      # responses from the OpenAPI specification instead.
      tools:
        mock: true
      # Security is explicitly disabled. It is possible to
      # run the authentication flow in MCP server even when
      # in mock mode, to help with debugging etc. We do not
      # need it for this example.
      security:
        auth:
          enabled: false

spring:
  ai:
    mcp:
      server:
        type: sync
        protocol: STATELESS