name: Prepare Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Override the release version, default is to removing -SNAPSHOT from the current version"
        required: false
      development_version:
        description: "Override the next development version, default is to incrementing the patch version"
        required: false

jobs:
  build:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: maven
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Prepare changelog
        run: ./.github/scripts/parse_and_update_changelog.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
      - name: Prepare maven release
        run: ./.github/scripts/prepare_maven_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
          DEVELOPMENT_VERSION: ${{ github.event.inputs.development_version }}
      - name: Create GitHub release
        run: ./.github/scripts/create_github_release.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
