name: Snyk vulnerability scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    env:
      SEVERITY_THRESHOLD: medium
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-21@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --severity-threshold=${{ env.SEVERITY_THRESHOLD }} --all-projects
          command: test
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        continue-on-error: true # Ensure monitor runs even if upload fails
        with:
          sarif_file: snyk.sarif
      - name: Run Snyk monitor to send results to Snyk
        uses: snyk/actions/maven-3-jdk-21@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=${{ env.SEVERITY_THRESHOLD }} --all-projects
          command: monitor
